/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarDetails;
import model.CarDetailsHistory;
/**
 *
 * @author shubhangisrivastava
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarDetailsHistory history;
    
    public ViewJPanel(CarDetailsHistory history) {
        initComponents();
        
        this.history = history;
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTtile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblCarName = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblNumberOfSeats = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        txtNumberOfSeats = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblMaintCertExpirationDt = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtManufactureYear = new javax.swing.JTextField();
        DtMaintenanceExp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblTtile.setFont(new java.awt.Font("Chalkboard", 1, 18)); // NOI18N
        lblTtile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTtile.setText("View Car Details");

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Name", "Availability", "Brand", "Manufacture Year", "Number Of Seats", "Serial Number", "Model Number", "City", "Maintenance Certification Expiration Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCars);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblCarName.setText("Car Name :");

        lblAvailability.setText("Availability :");

        lblBrand.setText("Brand :");

        lblManufactureYear.setText("Manufacture Year :");

        lblNumberOfSeats.setText("Number Of Seats :");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        lblSerialNumber.setText("Serial Number :");

        lblModelNumber.setText("Model Number :");

        txtNumberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfSeatsActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        lblCity.setText("City :");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblMaintCertExpirationDt.setText("Maintenance Certification Expiration Date :");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTtile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addGap(7, 7, 7)
                .addComponent(btnDelete)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarName)
                    .addComponent(lblAvailability)
                    .addComponent(lblBrand)
                    .addComponent(lblManufactureYear)
                    .addComponent(lblNumberOfSeats)
                    .addComponent(lblSerialNumber)
                    .addComponent(lblModelNumber)
                    .addComponent(lblCity)
                    .addComponent(lblMaintCertExpirationDt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarName)
                    .addComponent(txtBrand)
                    .addComponent(txtSerialNumber)
                    .addComponent(txtModelNumber)
                    .addComponent(txtCity)
                    .addComponent(txtNumberOfSeats)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(txtManufactureYear)
                    .addComponent(DtMaintenanceExp))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTtile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(lblCarName)
                                                            .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(17, 17, 17)
                                                        .addComponent(lblAvailability)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblBrand))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblManufactureYear)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNumberOfSeats))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSerialNumber))
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblModelNumber))
                            .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCity))
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaintCertExpirationDt)
                    .addComponent(DtMaintenanceExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
       int selectedRowIndex = tblCars.getSelectedRow();
       
       if(selectedRowIndex<0) {
           JOptionPane.showMessageDialog(this, "Please select a row to delete");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
       CarDetails selectedCars = (CarDetails) model.getValueAt(selectedRowIndex, 0);
       
       history.deleteCars(selectedCars);
       
       JOptionPane.showMessageDialog(this, "Car Details Deleted.");
       
       populateTable();
           


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        int selectedRowIndex = tblCars.getSelectedRow();
       
       if(selectedRowIndex<0) {
           JOptionPane.showMessageDialog(this, "Please select a row to delete");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
       CarDetails selectedCars = (CarDetails) model.getValueAt(selectedRowIndex, 0);
       
       txtCarName.setText(String.valueOf(selectedCars.getCar_name()));
       txtAvailability.setText(String.valueOf(selectedCars.getAvailability()));
       txtBrand.setText((String.valueOf(selectedCars.getBrand())));
       txtManufactureYear.setText(String.valueOf(selectedCars.getManufacture_year()));
       txtNumberOfSeats.setText(String.valueOf(selectedCars.getMin_max_seats()));
       txtSerialNumber.setText(String.valueOf(selectedCars.getSerial_number()));
       txtModelNumber.setText(String.valueOf(selectedCars.getModel_num()));
       txtCity.setText(String.valueOf(selectedCars.getCity()));
       DtMaintenanceExp.setText(String.valueOf(selectedCars.getMaint_cert_expiration_dt()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtNumberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfSeatsActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        DefaultTableModel model =(DefaultTableModel) tblCars.getModel();
        int selectedRowIndex = tblCars.getSelectedRow();
        
        String car_name = model.getValueAt(selectedRowIndex, 0).toString();
        String availability = model.getValueAt(selectedRowIndex, 1).toString();
        String brand = model.getValueAt(selectedRowIndex, 2).toString();
        String manufacture_dt = model.getValueAt(selectedRowIndex, 3).toString();
        String min_max_seats = model.getValueAt(selectedRowIndex, 4).toString();
        String Serial_Number = model.getValueAt(selectedRowIndex, 5).toString();
        String model_number = model.getValueAt(selectedRowIndex, 6).toString();
        String city = model.getValueAt(selectedRowIndex, 7).toString();
        String maintenance_expiration_dt = model.getValueAt(selectedRowIndex, 8).toString();
        
        
        String newCar_Name = JOptionPane.showInputDialog(null, "Enter new Car Name", car_name);
        String newAvailability = JOptionPane.showInputDialog(null, "Enter new Availability", availability);
        String newBrand = JOptionPane.showInputDialog(null, "Enter new Brand name", brand);
        String newManufacture_dt = JOptionPane.showInputDialog(null, "Enter new Manufacturing Date", manufacture_dt);
        String newMin_max_seats = JOptionPane.showInputDialog(null, "Enter new number of seats", min_max_seats);
        String newSerial_Number = JOptionPane.showInputDialog(null, "Enter new Serial Number", Serial_Number);
        String newModelNumber = JOptionPane.showInputDialog(null, "Enter new Model Number", model_number);
        String newCity = JOptionPane.showInputDialog(null, "Enter new City", city);
        String newMaintenance_expiration_dt = JOptionPane.showInputDialog(null, "Enter new Serial Number", maintenance_expiration_dt);
        
        model.setValueAt(newCar_Name, selectedRowIndex, 0);
        model.setValueAt(newAvailability, selectedRowIndex, 1);
        model.setValueAt(newBrand, selectedRowIndex, 2);
        model.setValueAt(newManufacture_dt, selectedRowIndex, 3);
        model.setValueAt(newMin_max_seats, selectedRowIndex, 4);
        model.setValueAt(newSerial_Number, selectedRowIndex, 5);
        model.setValueAt(newModelNumber, selectedRowIndex, 6);
        model.setValueAt(newCity, selectedRowIndex, 7);
        model.setValueAt(newMaintenance_expiration_dt, selectedRowIndex, 8);   
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DtMaintenanceExp;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintCertExpirationDt;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNumberOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTtile;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtNumberOfSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
    
    DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
    model.setRowCount(0);
    
    for(CarDetails cd : history.getHistory()) {
        
        Object[] row = new Object[9];
        row[0] = cd;
        if(cd.getAvailability() == "yes"){
            row[1]="Yes";
       } else if(cd.getAvailability() == "no"){
              row[1]="No";
          }else{
       row[1] = "No";
     }
        row[2] = cd.getBrand();
        row[3] = cd.getManufacture_year();
        row[4] = cd.getMin_max_seats();
        row[5] = cd.getSerial_number();
        row[6] = cd.getModel_num();
        row[7] = cd.getCity();
        row[8] = cd.getMaint_cert_expiration_dt();
        
        model.addRow(row);
    }
    }
}
